- action:
  - data:
      entity_id: group.all_switches
    service: homeassistant.turn_on
  alias: Turn On Indoor Lighting 45m Before Sunset
  condition:
  - condition: state
    entity_id: group.family
    state: home
  id: '1519742168246'
  trigger:
  - event: sunset
    offset: -00:45:00
    platform: sun
- action:
  - data:
      entity_id: group.indoorlighting
    service: homeassistant.turn_off
  alias: Turn Off Indoor Lights at 10:15 PM
  condition: []
  id: '1519742310300'
  trigger:
  - at: '22:15:00'
    platform: time
- action:
  - data:
      message: Abby just arrived home.
    service: notify.telegram
  alias: A is Home Telegram Notification
  condition: []
  id: '1519742558541'
  initial_state: false
  trigger:
  - entity_id: device_tracker.64bc0c45ea9b
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: Abby is away from home.
    service: notify.telegram
  alias: A is Away from Home Telegram Notification
  condition: []
  id: '1519742626294'
  initial_state: false
  trigger:
  - entity_id: device_tracker.64bc0c45ea9b
    from: home
    platform: state
    to: not_home
- action:
  - service: shell_command.heartbeat
  alias: HASS.IO Heartbeat to healthchecks.io
  condition: []
  id: '1519742778289'
  trigger:
  - minutes: /15
    seconds: 0
    platform: time
