- id: '1568564465578'
  alias: All Lights Off 10:00 PM
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - entity_id: switch.ge_12722_onoff_relay_switch_4
    service: switch.turn_off
  - entity_id: switch.ge_12722_onoff_relay_switch_3
    service: switch.turn_off
  - entity_id: switch.ge_12722_onoff_relay_switch_5
    service: switch.turn_off
- id: '1576357904687'
  alias: Playroom No Motion - Lights Off
  description: ''
  trigger:
  - entity_id: binary_sensor.playroom_occupancy
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: switch.ge_12722_onoff_relay_switch_5
    service: homeassistant.turn_off
- id: '1576358074376'
  alias: Living Room Motion - Lights On
  description: ''
  trigger:
  - entity_id: binary_sensor.living_room_occupancy
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.ge_12722_onoff_relay_switch_4
    service: homeassistant.turn_on
- id: '1576358404850'
  alias: Vivienne's Room No Motion - Lights Off
  description: ''
  trigger:
  - entity_id: binary_sensor.viviennes_room_occupancy
    for: 00:30:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - entity_id: switch.ge_14291_onoff_relay_switch_2
    service: homeassistant.turn_off
- id: '1519742778289'
  alias: HASS.IO Heartbeat to healthchecks.io
  description: ''
  trigger:
    platform: time_pattern
    minutes: /15
  condition: []
  action:
  - service: shell_command.healthcheck
- id: '1544582567121'
  alias: Turn Off Christmas Lights
  trigger:
  - at: '23:59'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_14284_outdoor_smart_switch_switch
    service: homeassistant.turn_off
- id: '1544583017280'
  alias: Turn On Christmas Lights
  trigger:
  - at: '17:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_14284_outdoor_smart_switch_switch
    service: homeassistant.turn_on
- id: '1580237118379'
  alias: Front Porch Light On at Sunset
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - entity_id: switch.jasco_products_14291_in_wall_smart_switch_switch_2
    service: light.turn_on
- id: '1580237333796'
  alias: Front Porch Light Off Everynight
  description: ''
  trigger:
  - at: '20:05'
    platform: time
  condition: []
  action:
  - entity_id: switch.jasco_products_14291_in_wall_smart_switch_switch_2
    service: light.turn_off
