- id: '1519742310300'
  alias: Ensure First Floor Lights are Off at 11:15 PM
  trigger:
  - at: '23:15'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_12722_onoff_relay_switch_4
    service: homeassistant.turn_off
  - data:
      entity_id: switch.ge_12722_onoff_relay_switch_3
    service: homeassistant.turn_off
  - data:
      entity_id: switch.ge_12722_onoff_relay_switch_5
    service: homeassistant.turn_off
- action:
  - data:
      message: Abby just arrived home.
    service: notify.telegram
  alias: A is Home Telegram Notification
  condition: []
  id: '1519742558541'
  initial_state: false
  trigger:
  - entity_id: device_tracker.64bc0c45ea9b
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: Abby is away from home.
    service: notify.telegram
  alias: A is Away from Home Telegram Notification
  condition: []
  id: '1519742626294'
  initial_state: false
  trigger:
  - entity_id: device_tracker.64bc0c45ea9b
    from: home
    platform: state
    to: not_home
- action:
  - service: shell_command.healthcheck
  alias: HASS.IO Heartbeat to healthchecks.io
  condition: []
  id: '1519742778289'
  trigger:
  - minutes: /15
    seconds: 0
    platform: time
- id: '1544582567121'
  alias: Turn Off Christmas Lights
  trigger:
  - at: '23:59'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_14284_outdoor_smart_switch_switch
    service: homeassistant.turn_off
- id: '1544583017280'
  alias: Turn On Christmas Lights
  trigger:
  - at: '18:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.ge_14284_outdoor_smart_switch_switch
    service: homeassistant.turn_on
