pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'
      
  - script: mv pipeline_secrets.yaml secrets.yaml
  
  - script: touch "ssl.cert"
  
  - script: touch "ssl.key"

  - script: mkdir "config"
  
  - script: touch "config/adbkey"

  - script: python -m pip install --upgrade pip
    
  - script: |
      pip install homeassistant

  - script: |
      hass -c . --script check_config
