
trigger: 
  - local-changes

schedules:
  -  cron: "0 12 * * 0"
     displayName: Weekly Sunday build
     branches:
       include:
       - main
     always: true

pool: Default

stages:
-  stage: CheckConfig
   jobs:
    - job: CheckConfigJob
      steps:
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
            addToPath: true
            architecture: 'x64'
                    
        #- script: copy pipeline_secrets.yaml secrets.yaml
        - powershell: Copy-Item pipeline_secrets.yaml secrets.yaml
      
        #- script: touch "ssl.cert"
        - powershell: New-Item "ssl.cert"
        
        #- script: touch "ssl.key"
        - powershell: New-Item "ssl.key"

        #- script: mkdir "config"
        - powershell: New-Item "config" -Type Directory
        
        #- script: touch "config/adbkey"
        - powershell: New-Item "config/adbkey" -Type Directory

        - script: python -m pip install --upgrade pip

        - script: python -m pip install homeassistant

        - script: python -m hass -c . --script check_config
