pool:
  vmImage: 'ubuntu-16.04' # other options: 'macOS-10.13', 'vs2017-win2016'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip
    
  - script: |
      pip install homeassistant

  - script: |
      - hass -c . --script check_config
