homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: ssl/cert.pem
  ssl_key: ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 1
  trusted_networks:
    - !secret trusted_networks

automation: !include automations.yaml

camera: !include_dir_list cameras

calendar:
  - platform: caldav
    url: !secret caldav_url
    username: !secret caldav_username
    password: !secret caldav_password
    calendars:
      - !secret calendar
      - us_federal_holidays

config:

device_tracker: !include_dir_list device_trackers

ecobee:
  api_key: !secret ecobee_api_key

group: !include groups.yaml

frontend:

hassio:

history:

influxdb: !include influxdb.yaml

logbook:

logger:
  default: error
  
map:

# broken
#media_player:
#  - platform: plex
  
notify: !include notify.yaml

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

panel_iframe: !include panels.yaml

recorder: !include recorder.yaml

script: !include scripts.yaml

sensor: !include_dir_list sensors

shell_command: !include shell_commands.yaml

sun:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

# broken
#usps:
#  username: !secret usps_username
#  password: !secret usps_password

updater:
  reporting: False

zone: !include zones.yaml

zwave:
  usb_path: /dev/ttyACM0