homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York

http:
#  api_password: !secret http_password
  base_url: !secret base_url
  ip_ban_enabled: true
  login_attempts_threshold: 5

automation: !include automations.yaml
automation old: !include_dir_merge_list automations

#camera: !include_dir_list cameras

default_config:

#device_tracker: !include_dir_list device_trackers

discovery:

ecobee:
  api_key: !secret ecobee_api_key

frontend:
  themes: !include themes.yaml

history:

#google_assistant:
#  project_id: !secret google_assistant_project_id
#  api_key: !secret google_cloud_platform_api_key
#  expose_by_default: false

logbook:

logger:
  default: error

lovelace:
  mode: yaml

media_player:

map:

tts:
  - platform: google_translate
    service_name: google_say

pi_hole:
  host: !secret dns_host
  verify_ssl: false

recorder:
  purge_keep_days: 5
  include:
    domains:
      - sensor
      - switch
  exclude:
    entities:
      - sensor.android_activity_sensor
      - sensor.android_battery_sensor
      - sensor.home_assistant_uptime
      - sensor.moon
      - sensor.pi_hole_ads_blocked_today
      - sensor.time

senseme:
  max_number_fans: 1

sensor: !include_dir_list sensors

#shell_command: !include includes/shell_commands.yaml

sun:

system_health:

#usps:
#  username: !secret usps_username
#  password: !secret usps_password

unifi:
  controllers:
    - host: unifi_host
      site: Myrna
#      ssid_filter:
#        - 'HomeSSID'
#        - 'IoTSSID'

updater:
  reporting: False

weather:
  - platform: darksky
    api_key: !secret darksky_api_key

zone: !include includes/zones.yaml

zwave:
  usb_path: /dev/ttyACM0
  