homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include includes/customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ip_ban_enabled: True
  login_attempts_threshold: 5
#  use_x_forwarded_for: True
  trusted_networks:
    - !secret trusted_network_1

automation: !include_dir_merge_list automations

camera: !include_dir_list cameras

coinbase:
  api_key: !secret coinbase_api_key
  api_secret: !secret coinbase_secret 
  exchange_rate_currencies:
    - BTC
    - ETH

config:

device_tracker: !include_dir_list device_trackers

discovery:

ecobee:
  api_key: !secret ecobee_api_key

frontend:

#group: !include includes/groups.yaml

history:

google_assistant:
  project_id: !secret google_assistant_project_id
  api_key: !secret google_cloud_platform_api_key
  #expose_by_default: false

logbook:

logger:
  default: error

media_player:
  - platform: plex

map:

notify: !include includes/notify.yaml

tts:
  - platform: google

recorder:
  purge_keep_days: 5
  include:
    domains:
      - sensor
      - switch

script: !include includes/scripts.yaml

sensor: !include_dir_list sensors

shell_command: !include includes/shell_commands.yaml

sun:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

#usps:
#  username: !secret usps_username
#  password: !secret usps_password

updater:
  reporting: False

zone: !include includes/zones.yaml

zwave:
  usb_path: /dev/ttyACM0