homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  base_url: !secret base_url
  ssl_certificate: ssl/cert.pem
  ssl_key: ssl/privkey.pem
  ip_ban_enabled: True
  login_attempts_threshold: 1


camera: !include_dir_list cameras

config:

device_tracker: !include_dir_list device_trackers

ecobee:
  api_key: !secret ecobee_api_key

frontend:
  extra_html_url:
    - /local/custom_ui/state-card-hline.html
  javascript_version: latest

hassio:

history:

logbook:

logger:
  default: error
  
map:

media_player:
  - platform: plex

sun:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_id

updater:
  reporting: False
  


# not working
#calendar:
#  - platform: caldav
#    url: !secret caldav_url
#    username: !secret caldav_username
#    password: !secret caldav_password
  
panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

# not setup yet
#media_player:
#  - platform: firetv
  
# not working
#usps:
#    username: !secret usps_username
#    password: !secret usps_password

zwave:
  usb_path: /dev/ttyACM0

# Includes
automation: !include automations.yaml
group: !include groups.yaml
influxdb: !include influxdb.yaml
notify: !include notify.yaml
panel_iframe: !include panels.yaml
recorder: !include recorder.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml