title: !secret home_title
views:
  - icon: mdi:home-assistant
    title: Home
    id: home
    cards:

      - type: entities
        title: Living Room
        show_header_toggle: false
        entities:
          - entity: switch.ge_12722_onoff_relay_switch_4
          - entity: sensor.living_room_temperature
            name: Temperature
          - entity: binary_sensor.living_room_occupancy
            name: Motion

      - type: entities
        title: Foyer
        show_header_toggle: false
        entities:
          - entity: sensor.my_ecobee_temperature
            name: Temperature
          - entity: binary_sensor.my_ecobee_occupancy
            name: Motion

      - type: entities
        title: Dining Room
        show_header_toggle: false
        entities:
          - entity: switch.ge_12722_onoff_relay_switch_3
      
      - type: entities
        title: Playroom
        show_header_toggle: false
        entities:
          - entity: switch.ge_12722_onoff_relay_switch_5
          - entity: sensor.playroom_temperature
            name: Temperature
          - entity: binary_sensor.playroom_occupancy
            name: Motion

      - type: entities
        title: Basement
        show_header_toggle: false
        entities:
          - entity: sensor.basement_temperature
            name: Temperature
          - entity: binary_sensor.basement_occupancy
            name: Motion

      - type: entities
        title: Master Bedroom
        show_header_toggle: false
        entities:
          - entity: sensor.master_bedroom_temperature
            name: Temperature
          - entity: binary_sensor.master_bedroom_occupancy
            name: Motion

      - type: entities
        title: !secret bedroom2_name
        show_header_toggle: false
        entities:
          - entity: switch.ge_14291_onoff_relay_switch_2
          - entity: !secret bedroom2_temperature
            name: Temperature
          - entity: !secret bedroom2_occupancy
            name: Motion

      - type: entities
        title: !secret bedroom3_name
        show_header_toggle: false
        entities:
          - entity: !secret bedroom3_temperature
            name: Temperature
          - entity: !secret bedroom3_occupancy
            name: Motion

      - type: entities
        title: !secret bedroom4_name
        show_header_toggle: false
        entities:
          - entity: !secret bedroom4_temperature
            name: Temperature
          - entity: !secret bedroom4_occupancy
            name: Motion
      
      - type: entities
        title: Outdoor Lights
        show_header_toggle: false
        entities:
          - entity: switch.ge_14284_outdoor_smart_switch_switch
            name: Christmas Lights

      - type: picture-entity
        entity: group.all_switches
        image: https://images.pexels.com/photos/106399/pexels-photo-106399.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260

      - type: entities
        title: Automations
        entities:
          #- automation.a_is_away_from_home_telegram_notification
          #- automation.a_is_home_telegram_notification
          - automation.ensure_first_floor_lights_are_off_at_11_15_pm
          - automation.hass_io_heartbeat_to_healthchecks_io
          - automation.turn_off_christmas_lights
          - automation.turn_on_christmas_lights

  - title: Climate
    id: climate
    cards:

      - type: weather-forecast
        entity: weather.dark_sky

      - type: entities
        title: Thermostat
        show_header_toggle: false
        entities:
          - entity: climate.my_ecobee
            name: Thermostat
          - entity: sensor.my_ecobee_temperature
            name: Temperature
          - entity: sensor.my_ecobee_humidity
            name: Humidity
          - entity: binary_sensor.my_ecobee_occupancy
            name: Motion
      
      - type: thermostat
        entity: climate.my_ecobee

      - type: history-graph
        title: Indoor Temperature History
        entities:
          - entity: sensor.master_bedroom_temperature
            name: Master Bedroom
          - entity: sensor.playroom_temperature
            name: Playroom
          - entity: sensor.living_room_temperature
            name: Living Room
          - entity: !secret bedroom2_temperature
            name: !secret bedroom2_name
          - entity: !secret bedroom3_temperature
            name: !secret bedroom3_name
          - entity: sensor.my_ecobee_temperature
            name: ecobee

  - title: Presence
    id: presence
    cards:

      - type: entities
        title: Joe's Phone
        show_header_toggle: false
        entities:
          - entity: device_tracker.joe
            name: Joe
          - entity: sensor.android_activity_sensor
            name: Activity Sensor
          - entity: sensor.android_battery_sensor
            name: Battery

      - type: map
        #aspect_ratio: 60%
        entities:
          - device_tracker.joe
          - zone.home
          - zone.work
          - zone.rec_center
          - zone.school

      - type: entities
        title: Drive Times
        shoe_header_toggle: false
        entities:
          - sensor.joe_s_home_travel_time
          - sensor.joe_s_morning_commute    
          
  - title: Security
    id: security
    cards:
    
      - type: entities
        title: Sun
        show_header_toggle: false
        entities:
          - sun.sun
          - sensor.moon
       
      - type: entities
        title: Home Assistant
        show_header_toggle: false
        entities:
          - sensor.home_assistant_uptime

      - type: entities
        title: Pi-hole
        entities:
          - sensor.pi_hole_ads_blocked_today
